#!/usr/bin/env python3
"""Create a minimal project-profile.yaml for research-guardrails."""

from __future__ import annotations

from pathlib import Path


DEFAULT_PROTECTED = [
    "data/",
    "datasets/",
    "raw/",
    "results/",
    "outputs/",
    "models/",
    "checkpoints/",
    "figures/",
    "manuscript/",
    "paper/",
]

DEFAULT_PRIVATE = [".env", ".ssh/", "secrets/", "private/", "confidential/"]


def safe_input(prompt: str) -> str:
    try:
        return input(prompt).strip()
    except EOFError:
        return ""


def ask_list(prompt: str, default: list[str]) -> list[str]:
    print(prompt)
    print("Default: " + ", ".join(default))
    raw = safe_input("Comma-separated paths, or Enter for default: ")
    if not raw:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


def ask_text(prompt: str, default: str) -> str:
    raw = safe_input(f"{prompt} [{default}]: ")
    return raw or default


def yaml_list(items: list[str], indent: int = 2) -> str:
    spaces = " " * indent
    return "\n".join(f'{spaces}- "{item}"' for item in items)


def main() -> int:
    print("research-guardrails project setup")
    print("Only three questions. Press Enter to keep recommended defaults.\n")

    project_name = ask_text("Project name", "My Research Project")
    protected = ask_list("1) Which directories contain irreplaceable data?", DEFAULT_PROTECTED)
    authoritative = ask_text("2) Current authoritative result directory or file", "results/")
    private = ask_list("3) Which private/confidential paths must never be uploaded?", DEFAULT_PRIVATE)

    output = Path("project-profile.yaml")
    content = f'''# Generated by research-guardrails/scripts/init_project_profile.py
project_name: "{project_name}"

protected_paths:
{yaml_list(protected)}

authoritative_results:
  - name: "main-results"
    path: "{authoritative}"
    notes: "Current authoritative evidence source for manuscript/report claims."

never_upload:
{yaml_list(private)}

default_actions:
  deletion: "move-to-quarantine"
  manuscript_numbers: "require-local-file-evidence"
  setup_questions: "ask-at-most-three"
'''
    output.write_text(content, encoding="utf-8")
    print(f"\nWrote {output.resolve()}")
    print("Review this file before sharing the repository.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
